$schema: "https://github.com/agile-learning-institute/stage0/blob/main/Schemas/product.schema.yaml"
$id: "https://github.com/agile-learning-institute/stage0_template_umbrella/blob/main/.stage0_template/Specifications/product.yaml"
title: Product and Organization Specifications for template testing

info:
  name: Mentor Hub
  description: A platform to connect mentors with engineers engaged in a life long learning journey.
  slug: mentorhub
  developer_cli: mh
  db_name: mentor_hub
  base_port: 8383

organization:
  name: Agile Learning Institute
  email: info@agile-learning-institute.com
  founded: 2024
  slug: agile-learning-institute
  git_host: https://github.com
  git_org: agile-learning-institute
  docker_host: ghcr.io
  docker_org: agile-learning-institute